<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="30178" started-at="2018-02-17T05:16:30Z" finished-at="2018-02-17T05:17:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="30178" started-at="2018-02-17T05:16:30Z" finished-at="2018-02-17T05:17:00Z">
      <class name="scenario_Component.ScenarioSearch">
        <test-method status="FAIL" signature="testValidSearch(java.util.Map)[pri:0, instance:scenario_Component.ScenarioSearch@78e67e0a]" name="testValidSearch" duration-ms="29849" started-at="2018-02-17T10:46:30Z" data-provider="dp_validSearch" finished-at="2018-02-17T10:47:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Execute_Flag=Y, TC_ID=EB_01, Script_name=ValidSearch, Search_Item=Reebok Shoes, Exp_Result=7,558 results, Order_Set=1.0}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected result = 7,558 results and Actual result =7,560 results, Hence Fail expected [7,558 results] but found [7,560 results]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected result = 7,558 results and Actual result =7,560 results, Hence Fail expected [7,558 results] but found [7,560 results]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at scenario_Component.ScenarioSearch.validateShoeCount(ScenarioSearch.java:79)
	at scenario_Component.ScenarioSearch.testValidSearch(ScenarioSearch.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidSearch -->
      </class> <!-- scenario_Component.ScenarioSearch -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
